/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/LargeBlockArmorBlock.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import modelUrl from './LargeBlockArmorBlock.glb'

export default function Model(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  const material = materials.material_1.clone()
  material.opacity=props.opacity;
  material.color=props.color;
  material.transparent=true;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Armor_Block.geometry} material={material} />
    </group>
  )
}

useGLTF.preload(modelUrl)
